#!/bin/sh

if [ "X$ARCH" = "X" ]
then
    OS=bloat-os
    MACHINE=`uname -m | sed -e 's/ //g' | sed -e 's?/?-?g'`
    SYSTEM=`uname -s | sed -e 's/ //g' | sed -e 's?/?-?g'`
    OS="${MACHINE}-${SYSTEM}"
    if [ -f ../scripts/gnu-os ]
    then	OS=`../scripts/gnu-os | sed s/unknown-//`
    fi
    if [ -f ../../scripts/gnu-os ]
    then	OS=`../../scripts/gnu-os | sed s/unknown-//`
    fi
else
    OS=${ARCH}
fi
echo $OS
